spring:
  cloud:
    stream:
      bindings:
        inputChannel-in-0:
          destination:  notification-topic
          group: admin-group
        outputChannel-out-0:
          destination:  notification-topic
      kafka:
        binder:
          brokers: localhost:9092